version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: brute-force-secret
    tty: true
    ports:
      - 5555:5555
    volumes:
      - ./:/go/src